---
- hosts: jenkins_servers
  max_fail_percentage: 1
  serial: 1
  accelerate: false
  sudo: true


  roles:
    - git
    - jenkins
    - jenkins-reconfigure-jobs
    - jenkins-seed-job
    - jenkins-deploy-xml
