---
- hosts: jenkins_servers
  max_fail_percentage: 1
  serial: 1
  accelerate: false
  sudo: true


  roles:
    - git
    - jenkins
    - jenkins-job-builder
    - jenkins-reconfigure-jobs-using-job-builder
    - jenkins-reconfigure-jobs-using-jinja2
    - jenkins-reconfigure-jobs-using-job-dsl
    - jenkins-kick-pipelines
