---
- hosts: zabbix_servers
  max_fail_percentage: 1
  serial: 1
  sudo: true

  roles:
    - flmmartins.disable-selinux
    - Azulinho.azulinho-google-dns
    - lborguetti.system-update
    - Azulinho.azulinho-apache
    - Azulinho.azulinho-mysql-server
    - Azulinho.azulinho-zabbix-server
    - Azulinho.azulinho-ssh-keys

- hosts: all
  max_fail_percentage: 1
  sudo: true

  roles:
    - Azulinho.azulinho-zabbix-agent
