---

- name: Install MySQL-python
  yum: name=MySQL-python state=present
  tags:
    - zabbix-agent

- name: install python zabbix api
  command: pip install pyzabbix
  tags:
    - zabbix-agent

- name: install zabbix agent
  command: yum --disableplugin=fastestmirror install zabbix22-agent python-pip -y
  tags:
    - zabbix-agent

- name: update config zabbix-agent
  template:
    src=zabbix_agent.conf
    dest=/etc/zabbix_agent.conf
  notify: restart zabbix agent
  tags:
    - zabbix-agent

- name: update config zabbix-agentd
  template:
    src=zabbix_agentd.conf
    dest=/etc/zabbix_agentd.conf
  notify: restart zabbix agentd
  tags:
    - zabbix-agent

