---

- name: Install MySQL-python
  yum: name=MySQL-python state=present
  tags:
    - zabbix

- name: install python zabbix api
  command: pip install pyzabbix
  tags:
    - zabbix

# Install zabbix packages
#
- name: install zabbix 2.2 and web stuff
  command: yum --disableplugin=fastestmirror install zabbix22 zabbix22-web-mysql zabbix22-server-mysql -y
  tags:
    - zabbix
    - zabbix-server

# Zabbix MySQL database initialisation steps:
# - should run only once
#
- include: mysql-setup.yml

# Configuration tasks for zabbix server:
#
- include: zabbix-server-configuration.yml

# Update Apache and PHP configuration for Zabbix
#
- include: apache-php.yml

