---

- name: install httplib2
  pip: name=httplib2
    state=present

- name: create /etc/jenkins_seed_jobs directories
  file: path={{ item }} state=directory
  with_items:
    - /etc/jenkins_seed_jobs
    - /etc/jenkins_seed_jobs/seeds
    - /etc/jenkins_seed_jobs/dsl

- name: upload jenkins seed jobs definitions
  copy: dest="/etc/jenkins_seed_jobs/seeds/{{ ''.join(item.split('/')[-1:]) }}"
    src={{ item }}
  with_fileglob:
    - seed_jobs_definitions/*
  register: upload

- name: upload jenkins DSL code
  synchronize: dest=/var/lib/jenkins/jobs/seed/workspace/ src=dsl/ recursive=yes delete=yes

- name: update permissions
  file: path=/var/lib/jenkins/jobs/seed/workspace/ recurse=yes owner=jenkins group=jenkins

- name: gather list of seed jobs
  command: ls /etc/jenkins_seed_jobs/seeds/
  register: seed_jobs

- name: upload new job and ignore errors if it already exists
  command: 'curl -X POST "http://localhost:8080/createItem?name={{item}}" --data-binary "@/etc/jenkins_seed_jobs/seeds/{{item}}" -H "Content-Type: text/xml"'
  with_items:
    - "{{ seed_jobs.stdout }}"

- name: update jobs if they already exist
  command: 'curl -X POST "http://localhost:8080/job/{{item}}/config.xml" --data-binary "@/etc/jenkins_seed_jobs/seeds/{{item}}" -H "Content-Type: text/xml"'
  with_items:
    - "{{ seed_jobs.stdout }}"

- name: deploy jobs
  command: 'curl "http://localhost:8080/job/{{item}}/build"'
  with_items:
    - "{{ seed_jobs.stdout }}"
