---

# Trigger pipelines, we need the first job to be built at least once
# so that we can visualise the full pipeline
#
- name: we need to wait for the seed job to finish
  wait_for: delay=90
  tags:
    - jenkins_pipeline

- name: kick first job in the pipeline
  uri: url="http://localhost:8080/job/{{item}}/buildWithParameters"
    follow_redirects=all
    method=GET
  with_items:
    - "{{ pipeline_first_jobs }}"
  tags:
    - jenkins_pipeline

