---

# Trigger pipelines, we need the first job to be built at least once
# so that we can visualise the full pipeline
#
- name: kick first job in the pipeline
  command: 'curl "http://localhost:8080/job/{{item}}/buildWithParameters"'
  with_items:
    - "{{ pipeline_first_jobs }}"
  tags:
    - jenkins_pipeline

